version: '3'

networks:
  common:
    driver: bridge

services:
  # comment this out to run just database
  monitor-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    container_name: monitor-app
    volumes:
      - ./src:/home/node/monitor/src
      - ./nodemon.json:/home/node/monitor/nodemon.json
    environment:
      - DB_HOST=mysql-db
    depends_on:
      - database
    ports:
      - "${APP_PORT}:${APP_PORT}"
    networks:
      - common
    command: npm run dev

  # can be run independently
  database:
    image: mysql
    container_name: mysql-db
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./.mysql:/var/lib/mysql
    environment:
      - MYSQL_HOST=$DB_HOST
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_USER=$DB_USERNAME
      - MYSQL_PASSWORD=$DB_PASSWORD
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
    expose:
      - $DB_PORT
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - common
