version: '3'

services:
  monitor-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/monitor/src
      - ./nodemon.json:/home/node/monitor/nodemon.json
    container_name: monitor-app
    depends_on:
      - database
    ports:
      - "${APP_PORT}:${APP_PORT}"
    command: npm run dev

  database:
    image: mysql:latest
    restart: always
    container_name: db-mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_PASSWORD=$DB_PASSWORD
      - MYSQL_USER=$DB_USERNAME
      - MYSQL_DATABASE=$DB_NAME
    ports:
      - "${DB_PORT}:${DB_PORT}"
